// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load .env.local first, then fall back to .env
config({ path: ".env.local" });
config({ path: ".env" });

const databaseUrl = process.env["DIRECT_URL"] || process.env["DATABASE_URL"];

if (!databaseUrl) {
  throw new Error(
    "DATABASE_URL or DIRECT_URL environment variable is required. " +
    "Please set it in .env.local or .env file."
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
